#ifndef __TBGAL_TOOLS_TEST_CALLS_HPP__
#define __TBGAL_TOOLS_TEST_CALLS_HPP__

#if TESTING_VECTOR_SPACE_DIMENSIONS >= 0
    MULTIPLICATION_TESTS(0, 0)
#if TESTING_VECTOR_SPACE_DIMENSIONS >= 1
    MULTIPLICATION_TESTS(0, 1)
    MULTIPLICATION_TESTS(1, 0)
    MULTIPLICATION_TESTS(1, 1)
#if TESTING_VECTOR_SPACE_DIMENSIONS >= 2
    MULTIPLICATION_TESTS(0, 2)
    MULTIPLICATION_TESTS(1, 2)
    MULTIPLICATION_TESTS(2, 0)
    MULTIPLICATION_TESTS(2, 1)
    MULTIPLICATION_TESTS(2, 2)
#if TESTING_VECTOR_SPACE_DIMENSIONS >= 3
    MULTIPLICATION_TESTS(0, 3)
    MULTIPLICATION_TESTS(1, 3)
    MULTIPLICATION_TESTS(2, 3)
    MULTIPLICATION_TESTS(3, 0)
    MULTIPLICATION_TESTS(3, 1)
    MULTIPLICATION_TESTS(3, 2)
    MULTIPLICATION_TESTS(3, 3)
#if TESTING_VECTOR_SPACE_DIMENSIONS >= 4
    MULTIPLICATION_TESTS(0, 4)
    MULTIPLICATION_TESTS(1, 4)
    MULTIPLICATION_TESTS(2, 4)
    MULTIPLICATION_TESTS(3, 4)
    MULTIPLICATION_TESTS(4, 0)
    MULTIPLICATION_TESTS(4, 1)
    MULTIPLICATION_TESTS(4, 2)
    MULTIPLICATION_TESTS(4, 3)
    MULTIPLICATION_TESTS(4, 4)
#if TESTING_VECTOR_SPACE_DIMENSIONS >= 5
    MULTIPLICATION_TESTS(0, 5)
    MULTIPLICATION_TESTS(1, 5)
    MULTIPLICATION_TESTS(2, 5)
    MULTIPLICATION_TESTS(3, 5)
    MULTIPLICATION_TESTS(4, 5)
    MULTIPLICATION_TESTS(5, 0)
    MULTIPLICATION_TESTS(5, 1)
    MULTIPLICATION_TESTS(5, 2)
    MULTIPLICATION_TESTS(5, 3)
    MULTIPLICATION_TESTS(5, 4)
    MULTIPLICATION_TESTS(5, 5)
#endif // TESTING_VECTOR_SPACE_DIMENSIONS >= 5
#endif // TESTING_VECTOR_SPACE_DIMENSIONS >= 4
#endif // TESTING_VECTOR_SPACE_DIMENSIONS >= 3
#endif // TESTING_VECTOR_SPACE_DIMENSIONS >= 2
#endif // TESTING_VECTOR_SPACE_DIMENSIONS >= 1
#endif // TESTING_VECTOR_SPACE_DIMENSIONS >= 0

#endif // __TBGAL_TOOLS_TEST_CALLS_HPP__
